[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[runner]
fastReruns = false
magicEnabled = false

[client]
showErrorDetails = true
toolbarMode = "minimal"
